auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: MemoRyAxis
url: http://memoryaxis.com
feed: /atom.xml
author_info: <a href="http://memoryaxis.com/">MemoRyAxis</a>
